name: Q1 - Copier TOTO.txt

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Créer le fichier Q1_archive_TOTO.txt
        run: |
          cp TOTO.txt Q1_archive_TOTO.txt

      - name: Commit et push
        continue-on-error: true
        run: |
          git config --global user.name "NicolasCHANTEUX"
          git config --global user.email "nicolas.chtx@gmail.com"
          git add Q1_archive_TOTO.txt
          git commit -m "Ajout Q1_archive_TOTO.txt" || echo "Rien à commiter"
          git push || echo "Rien à pousser"
